[0m20:54:10.355931 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x763047cf7890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x763046d2b920>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x76304560be60>]}


============================== 20:54:10.363052 | 8adaaf66-4b80-48a6-b63c-c40ad4162b19 ==============================
[0m20:54:10.363052 [info ] [MainThread]: Running with dbt=1.9.3
[0m20:54:10.363533 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '/home/ubuntu/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt test', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m20:54:10.364838 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/ubuntu/SP25_DS5111_xxa4aa/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m20:54:10.366849 [debug] [MainThread]: Resource report: {"command_name": "test", "command_success": false, "command_wall_clock_time": 0.07906856, "process_in_blocks": "55464", "process_kernel_time": 0.199547, "process_mem_max_rss": "91692", "process_out_blocks": "8", "process_user_time": 1.519291}
[0m20:54:10.367205 [debug] [MainThread]: Command `dbt test` failed at 20:54:10.367121 after 0.08 seconds
[0m20:54:10.367516 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x763045913500>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7630456ff380>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7630456473b0>]}
[0m20:54:10.367836 [debug] [MainThread]: Flushing usage events
[0m20:54:10.380922 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m20:54:20.905413 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x741246a5f800>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x741246a5c740>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x741245f9ae70>]}


============================== 20:54:20.909766 | 6787aebb-fa28-43c5-bac0-491a1ae73a06 ==============================
[0m20:54:20.909766 [info ] [MainThread]: Running with dbt=1.9.3
[0m20:54:20.910418 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/ubuntu/.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt test', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m20:54:20.910809 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/ubuntu/SP25_DS5111_xxa4aa/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m20:54:20.912739 [debug] [MainThread]: Resource report: {"command_name": "test", "command_success": false, "command_wall_clock_time": 0.06755231, "process_in_blocks": "248", "process_kernel_time": 0.123421, "process_mem_max_rss": "91816", "process_out_blocks": "16", "process_user_time": 1.475755}
[0m20:54:20.913446 [debug] [MainThread]: Command `dbt test` failed at 20:54:20.913010 after 0.07 seconds
[0m20:54:20.913762 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x741246132a50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x741245dd8e30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x741245ddbc80>]}
[0m20:54:20.914054 [debug] [MainThread]: Flushing usage events
[0m20:54:20.924270 [debug] [MainThread]: An error was encountered while trying to flush usage events
